namespace: nginx
replicaCount: 1
image:
  repository: hinata/nginx-forward-proxy
  tag: latest
service:
  port: 80
  targetPort: 3128
nodeSelector:
  kubernetes.io/os: linux
  kubernetes.io/arch: amd64

