apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-forward-proxy
  namespace: {{ .Values.namespace }}
  labels:
    app: nginx-forward-proxy
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: nginx-forward-proxy
  template:
    metadata:
      labels:
        app: nginx-forward-proxy
    spec:
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      containers:
      - name: nginx-forward-proxy
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
