apiVersion: v1
kind: Service
metadata:
  name: nginx-forward-proxy
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: nginx-forward-proxy
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
